const START = 'feb5d853-f51b-4744-a685-adb3d58f1449';

const CREATE_PLAYERS = {
  "fields": [
    {
      "fieldType": "NORMAL",
      "position": 1
    },
    {
      "fieldType": "NORMAL",
      "position": 2
    },
    {
      "fieldType": "NORMAL",
      "position": 3
    },
    {
      "fieldType": "NORMAL",
      "position": 4
    },
    {
      "fieldType": "TRAP",
      "position": 5
    },
    {
      "fieldType": "NORMAL",
      "position": 6
    },
    {
      "fieldType": "TRAP",
      "position": 7
    },
    {
      "fieldType": "NORMAL",
      "position": 8
    },
    {
      "fieldType": "BONUS",
      "position": 9
    },
    {
      "fieldType": "NORMAL",
      "position": 10
    },
    {
      "fieldType": "TRAP",
      "position": 11
    },
    {
      "fieldType": "NORMAL",
      "position": 12
    },
    {
      "fieldType": "BONUS",
      "position": 13
    },
    {
      "fieldType": "NORMAL",
      "position": 14
    },
    {
      "fieldType": "TRAP",
      "position": 15
    },
    {
      "fieldType": "NORMAL",
      "position": 16
    },
    {
      "fieldType": "NORMAL",
      "position": 17
    },
    {
      "fieldType": "BONUS",
      "position": 18
    },
    {
      "fieldType": "BONUS",
      "position": 19
    },
    {
      "fieldType": "NORMAL",
      "position": 20
    },
    {
      "fieldType": "NORMAL",
      "position": 21
    },
    {
      "fieldType": "TRAP",
      "position": 22
    },
    {
      "fieldType": "BONUS",
      "position": 23
    },
    {
      "fieldType": "NORMAL",
      "position": 24
    },
    {
      "fieldType": "NORMAL",
      "position": 25
    },
    {
      "fieldType": "NORMAL",
      "position": 26
    },
    {
      "fieldType": "NORMAL",
      "position": 27
    },
    {
      "fieldType": "NORMAL",
      "position": 28
    },
    {
      "fieldType": "NORMAL",
      "position": 29
    },
    {
      "fieldType": "NORMAL",
      "position": 30
    }
  ],
  "players": [
    {
      "name": "Player 3",
      "field": 0,
      "previousField": null,
      "joker": false,
      "skipNextRound": false,
      "lastGamingSituation": null
    },
    {
      "name": "Player 1",
      "field": 0,
      "previousField": null,
      "joker": false,
      "skipNextRound": false,
      "lastGamingSituation": null
    },
    {
      "name": "Player 2",
      "field": 0,
      "previousField": null,
      "joker": false,
      "skipNextRound": false,
      "lastGamingSituation": null
    }
  ],
  "nextPlayer": {
    "name": "Player 3",
    "field": 0,
    "previousField": null,
    "joker": false,
    "skipNextRound": false,
    "lastGamingSituation": null
  },
  "winner": null,
  "id": "feb5d853-f51b-4744-a685-adb3d58f1449"
};

const NEXT = [
  {"fields":[{"fieldType":"NORMAL","position":1},{"fieldType":"NORMAL","position":2},{"fieldType":"NORMAL","position":3},{"fieldType":"NORMAL","position":4},{"fieldType":"TRAP","position":5},{"fieldType":"NORMAL","position":6},{"fieldType":"TRAP","position":7},{"fieldType":"NORMAL","position":8},{"fieldType":"BONUS","position":9},{"fieldType":"NORMAL","position":10},{"fieldType":"TRAP","position":11},{"fieldType":"NORMAL","position":12},{"fieldType":"BONUS","position":13},{"fieldType":"NORMAL","position":14},{"fieldType":"TRAP","position":15},{"fieldType":"NORMAL","position":16},{"fieldType":"NORMAL","position":17},{"fieldType":"BONUS","position":18},{"fieldType":"BONUS","position":19},{"fieldType":"NORMAL","position":20},{"fieldType":"NORMAL","position":21},{"fieldType":"TRAP","position":22},{"fieldType":"BONUS","position":23},{"fieldType":"NORMAL","position":24},{"fieldType":"NORMAL","position":25},{"fieldType":"NORMAL","position":26},{"fieldType":"NORMAL","position":27},{"fieldType":"NORMAL","position":28},{"fieldType":"NORMAL","position":29},{"fieldType":"NORMAL","position":30}],"players":[{"name":"Player 3","field":2,"previousField":0,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 3' moved from field number 0 to field number 2."},{"name":"Player 1","field":0,"previousField":null,"joker":false,"skipNextRound":false,"lastGamingSituation":null},{"name":"Player 2","field":0,"previousField":null,"joker":false,"skipNextRound":false,"lastGamingSituation":null}],"nextPlayer":{"name":"Player 1","field":0,"previousField":null,"joker":false,"skipNextRound":false,"lastGamingSituation":null},"winner":null,"id":"feb5d853-f51b-4744-a685-adb3d58f1449"},
  {"fields":[{"fieldType":"NORMAL","position":1},{"fieldType":"NORMAL","position":2},{"fieldType":"NORMAL","position":3},{"fieldType":"NORMAL","position":4},{"fieldType":"TRAP","position":5},{"fieldType":"NORMAL","position":6},{"fieldType":"TRAP","position":7},{"fieldType":"NORMAL","position":8},{"fieldType":"BONUS","position":9},{"fieldType":"NORMAL","position":10},{"fieldType":"TRAP","position":11},{"fieldType":"NORMAL","position":12},{"fieldType":"BONUS","position":13},{"fieldType":"NORMAL","position":14},{"fieldType":"TRAP","position":15},{"fieldType":"NORMAL","position":16},{"fieldType":"NORMAL","position":17},{"fieldType":"BONUS","position":18},{"fieldType":"BONUS","position":19},{"fieldType":"NORMAL","position":20},{"fieldType":"NORMAL","position":21},{"fieldType":"TRAP","position":22},{"fieldType":"BONUS","position":23},{"fieldType":"NORMAL","position":24},{"fieldType":"NORMAL","position":25},{"fieldType":"NORMAL","position":26},{"fieldType":"NORMAL","position":27},{"fieldType":"NORMAL","position":28},{"fieldType":"NORMAL","position":29},{"fieldType":"NORMAL","position":30}],"players":[{"name":"Player 3","field":2,"previousField":0,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 3' moved from field number 0 to field number 2."},{"name":"Player 1","field":4,"previousField":0,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 1' moved from field number 0 to field number 4."},{"name":"Player 2","field":0,"previousField":null,"joker":false,"skipNextRound":false,"lastGamingSituation":null}],"nextPlayer":{"name":"Player 2","field":0,"previousField":null,"joker":false,"skipNextRound":false,"lastGamingSituation":null},"winner":null,"id":"feb5d853-f51b-4744-a685-adb3d58f1449"},
  {"fields":[{"fieldType":"NORMAL","position":1},{"fieldType":"NORMAL","position":2},{"fieldType":"NORMAL","position":3},{"fieldType":"NORMAL","position":4},{"fieldType":"TRAP","position":5},{"fieldType":"NORMAL","position":6},{"fieldType":"TRAP","position":7},{"fieldType":"NORMAL","position":8},{"fieldType":"BONUS","position":9},{"fieldType":"NORMAL","position":10},{"fieldType":"TRAP","position":11},{"fieldType":"NORMAL","position":12},{"fieldType":"BONUS","position":13},{"fieldType":"NORMAL","position":14},{"fieldType":"TRAP","position":15},{"fieldType":"NORMAL","position":16},{"fieldType":"NORMAL","position":17},{"fieldType":"BONUS","position":18},{"fieldType":"BONUS","position":19},{"fieldType":"NORMAL","position":20},{"fieldType":"NORMAL","position":21},{"fieldType":"TRAP","position":22},{"fieldType":"BONUS","position":23},{"fieldType":"NORMAL","position":24},{"fieldType":"NORMAL","position":25},{"fieldType":"NORMAL","position":26},{"fieldType":"NORMAL","position":27},{"fieldType":"NORMAL","position":28},{"fieldType":"NORMAL","position":29},{"fieldType":"NORMAL","position":30}],"players":[{"name":"Player 3","field":2,"previousField":0,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 3' moved from field number 0 to field number 2."},{"name":"Player 1","field":4,"previousField":0,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 1' moved from field number 0 to field number 4."},{"name":"Player 2","field":3,"previousField":0,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 2' moved from field number 0 to field number 3."}],"nextPlayer":{"name":"Player 3","field":2,"previousField":0,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 3' moved from field number 0 to field number 2."},"winner":null,"id":"feb5d853-f51b-4744-a685-adb3d58f1449"},
  {"fields":[{"fieldType":"NORMAL","position":1},{"fieldType":"NORMAL","position":2},{"fieldType":"NORMAL","position":3},{"fieldType":"NORMAL","position":4},{"fieldType":"TRAP","position":5},{"fieldType":"NORMAL","position":6},{"fieldType":"TRAP","position":7},{"fieldType":"NORMAL","position":8},{"fieldType":"BONUS","position":9},{"fieldType":"NORMAL","position":10},{"fieldType":"TRAP","position":11},{"fieldType":"NORMAL","position":12},{"fieldType":"BONUS","position":13},{"fieldType":"NORMAL","position":14},{"fieldType":"TRAP","position":15},{"fieldType":"NORMAL","position":16},{"fieldType":"NORMAL","position":17},{"fieldType":"BONUS","position":18},{"fieldType":"BONUS","position":19},{"fieldType":"NORMAL","position":20},{"fieldType":"NORMAL","position":21},{"fieldType":"TRAP","position":22},{"fieldType":"BONUS","position":23},{"fieldType":"NORMAL","position":24},{"fieldType":"NORMAL","position":25},{"fieldType":"NORMAL","position":26},{"fieldType":"NORMAL","position":27},{"fieldType":"NORMAL","position":28},{"fieldType":"NORMAL","position":29},{"fieldType":"NORMAL","position":30}],"players":[{"name":"Player 3","field":6,"previousField":2,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 3' moved from field number 2 to field number 6."},{"name":"Player 1","field":4,"previousField":0,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 1' moved from field number 0 to field number 4."},{"name":"Player 2","field":3,"previousField":0,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 2' moved from field number 0 to field number 3."}],"nextPlayer":{"name":"Player 1","field":4,"previousField":0,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 1' moved from field number 0 to field number 4."},"winner":null,"id":"feb5d853-f51b-4744-a685-adb3d58f1449"},
  {"fields":[{"fieldType":"NORMAL","position":1},{"fieldType":"NORMAL","position":2},{"fieldType":"NORMAL","position":3},{"fieldType":"NORMAL","position":4},{"fieldType":"TRAP","position":5},{"fieldType":"NORMAL","position":6},{"fieldType":"TRAP","position":7},{"fieldType":"NORMAL","position":8},{"fieldType":"BONUS","position":9},{"fieldType":"NORMAL","position":10},{"fieldType":"TRAP","position":11},{"fieldType":"NORMAL","position":12},{"fieldType":"BONUS","position":13},{"fieldType":"NORMAL","position":14},{"fieldType":"TRAP","position":15},{"fieldType":"NORMAL","position":16},{"fieldType":"NORMAL","position":17},{"fieldType":"BONUS","position":18},{"fieldType":"BONUS","position":19},{"fieldType":"NORMAL","position":20},{"fieldType":"NORMAL","position":21},{"fieldType":"TRAP","position":22},{"fieldType":"BONUS","position":23},{"fieldType":"NORMAL","position":24},{"fieldType":"NORMAL","position":25},{"fieldType":"NORMAL","position":26},{"fieldType":"NORMAL","position":27},{"fieldType":"NORMAL","position":28},{"fieldType":"NORMAL","position":29},{"fieldType":"NORMAL","position":30}],"players":[{"name":"Player 3","field":6,"previousField":2,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 3' moved from field number 2 to field number 6."},{"name":"Player 1","field":8,"previousField":4,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 1' moved from field number 4 to field number 8."},{"name":"Player 2","field":3,"previousField":0,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 2' moved from field number 0 to field number 3."}],"nextPlayer":{"name":"Player 2","field":3,"previousField":0,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 2' moved from field number 0 to field number 3."},"winner":null,"id":"feb5d853-f51b-4744-a685-adb3d58f1449"},
  {"fields":[{"fieldType":"NORMAL","position":1},{"fieldType":"NORMAL","position":2},{"fieldType":"NORMAL","position":3},{"fieldType":"NORMAL","position":4},{"fieldType":"TRAP","position":5},{"fieldType":"NORMAL","position":6},{"fieldType":"TRAP","position":7},{"fieldType":"NORMAL","position":8},{"fieldType":"BONUS","position":9},{"fieldType":"NORMAL","position":10},{"fieldType":"TRAP","position":11},{"fieldType":"NORMAL","position":12},{"fieldType":"BONUS","position":13},{"fieldType":"NORMAL","position":14},{"fieldType":"TRAP","position":15},{"fieldType":"NORMAL","position":16},{"fieldType":"NORMAL","position":17},{"fieldType":"BONUS","position":18},{"fieldType":"BONUS","position":19},{"fieldType":"NORMAL","position":20},{"fieldType":"NORMAL","position":21},{"fieldType":"TRAP","position":22},{"fieldType":"BONUS","position":23},{"fieldType":"NORMAL","position":24},{"fieldType":"NORMAL","position":25},{"fieldType":"NORMAL","position":26},{"fieldType":"NORMAL","position":27},{"fieldType":"NORMAL","position":28},{"fieldType":"NORMAL","position":29},{"fieldType":"NORMAL","position":30}],"players":[{"name":"Player 3","field":6,"previousField":2,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 3' moved from field number 2 to field number 6."},{"name":"Player 1","field":8,"previousField":4,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 1' moved from field number 4 to field number 8."},{"name":"Player 2","field":6,"previousField":3,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 2' moved from field number 3 to field number 6."}],"nextPlayer":{"name":"Player 3","field":6,"previousField":2,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 3' moved from field number 2 to field number 6."},"winner":null,"id":"feb5d853-f51b-4744-a685-adb3d58f1449"},
  {"fields":[{"fieldType":"NORMAL","position":1},{"fieldType":"NORMAL","position":2},{"fieldType":"NORMAL","position":3},{"fieldType":"NORMAL","position":4},{"fieldType":"TRAP","position":5},{"fieldType":"NORMAL","position":6},{"fieldType":"TRAP","position":7},{"fieldType":"NORMAL","position":8},{"fieldType":"BONUS","position":9},{"fieldType":"NORMAL","position":10},{"fieldType":"TRAP","position":11},{"fieldType":"NORMAL","position":12},{"fieldType":"BONUS","position":13},{"fieldType":"NORMAL","position":14},{"fieldType":"TRAP","position":15},{"fieldType":"NORMAL","position":16},{"fieldType":"NORMAL","position":17},{"fieldType":"BONUS","position":18},{"fieldType":"BONUS","position":19},{"fieldType":"NORMAL","position":20},{"fieldType":"NORMAL","position":21},{"fieldType":"TRAP","position":22},{"fieldType":"BONUS","position":23},{"fieldType":"NORMAL","position":24},{"fieldType":"NORMAL","position":25},{"fieldType":"NORMAL","position":26},{"fieldType":"NORMAL","position":27},{"fieldType":"NORMAL","position":28},{"fieldType":"NORMAL","position":29},{"fieldType":"NORMAL","position":30}],"players":[{"name":"Player 3","field":8,"previousField":6,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 3' moved from field number 6 to field number 8."},{"name":"Player 1","field":8,"previousField":4,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 1' moved from field number 4 to field number 8."},{"name":"Player 2","field":6,"previousField":3,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 2' moved from field number 3 to field number 6."}],"nextPlayer":{"name":"Player 1","field":8,"previousField":4,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 1' moved from field number 4 to field number 8."},"winner":null,"id":"feb5d853-f51b-4744-a685-adb3d58f1449"},
  {"fields":[{"fieldType":"NORMAL","position":1},{"fieldType":"NORMAL","position":2},{"fieldType":"NORMAL","position":3},{"fieldType":"NORMAL","position":4},{"fieldType":"TRAP","position":5},{"fieldType":"NORMAL","position":6},{"fieldType":"TRAP","position":7},{"fieldType":"NORMAL","position":8},{"fieldType":"BONUS","position":9},{"fieldType":"NORMAL","position":10},{"fieldType":"TRAP","position":11},{"fieldType":"NORMAL","position":12},{"fieldType":"BONUS","position":13},{"fieldType":"NORMAL","position":14},{"fieldType":"TRAP","position":15},{"fieldType":"NORMAL","position":16},{"fieldType":"NORMAL","position":17},{"fieldType":"BONUS","position":18},{"fieldType":"BONUS","position":19},{"fieldType":"NORMAL","position":20},{"fieldType":"NORMAL","position":21},{"fieldType":"TRAP","position":22},{"fieldType":"BONUS","position":23},{"fieldType":"NORMAL","position":24},{"fieldType":"NORMAL","position":25},{"fieldType":"NORMAL","position":26},{"fieldType":"NORMAL","position":27},{"fieldType":"NORMAL","position":28},{"fieldType":"NORMAL","position":29},{"fieldType":"NORMAL","position":30}],"players":[{"name":"Player 3","field":8,"previousField":6,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 3' moved from field number 6 to field number 8."},{"name":"Player 1","field":10,"previousField":8,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 1' moved from field number 8 to field number 10."},{"name":"Player 2","field":6,"previousField":3,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 2' moved from field number 3 to field number 6."}],"nextPlayer":{"name":"Player 2","field":6,"previousField":3,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 2' moved from field number 3 to field number 6."},"winner":null,"id":"feb5d853-f51b-4744-a685-adb3d58f1449"},
  {"fields":[{"fieldType":"NORMAL","position":1},{"fieldType":"NORMAL","position":2},{"fieldType":"NORMAL","position":3},{"fieldType":"NORMAL","position":4},{"fieldType":"TRAP","position":5},{"fieldType":"NORMAL","position":6},{"fieldType":"TRAP","position":7},{"fieldType":"NORMAL","position":8},{"fieldType":"BONUS","position":9},{"fieldType":"NORMAL","position":10},{"fieldType":"TRAP","position":11},{"fieldType":"NORMAL","position":12},{"fieldType":"BONUS","position":13},{"fieldType":"NORMAL","position":14},{"fieldType":"TRAP","position":15},{"fieldType":"NORMAL","position":16},{"fieldType":"NORMAL","position":17},{"fieldType":"BONUS","position":18},{"fieldType":"BONUS","position":19},{"fieldType":"NORMAL","position":20},{"fieldType":"NORMAL","position":21},{"fieldType":"TRAP","position":22},{"fieldType":"BONUS","position":23},{"fieldType":"NORMAL","position":24},{"fieldType":"NORMAL","position":25},{"fieldType":"NORMAL","position":26},{"fieldType":"NORMAL","position":27},{"fieldType":"NORMAL","position":28},{"fieldType":"NORMAL","position":29},{"fieldType":"NORMAL","position":30}],"players":[{"name":"Player 3","field":8,"previousField":6,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 3' moved from field number 6 to field number 8."},{"name":"Player 1","field":10,"previousField":8,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 1' moved from field number 8 to field number 10."},{"name":"Player 2","field":11,"previousField":6,"joker":false,"skipNextRound":false,"lastGamingSituation":"Player 2 has hit a bonus field of the type 'Move two fields forward'. The player 'Player 2' moved from field number 6 to field number 11."}],"nextPlayer":{"name":"Player 3","field":8,"previousField":6,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 3' moved from field number 6 to field number 8."},"winner":null,"id":"feb5d853-f51b-4744-a685-adb3d58f1449"},
  {"fields":[{"fieldType":"NORMAL","position":1},{"fieldType":"NORMAL","position":2},{"fieldType":"NORMAL","position":3},{"fieldType":"NORMAL","position":4},{"fieldType":"TRAP","position":5},{"fieldType":"NORMAL","position":6},{"fieldType":"TRAP","position":7},{"fieldType":"NORMAL","position":8},{"fieldType":"BONUS","position":9},{"fieldType":"NORMAL","position":10},{"fieldType":"TRAP","position":11},{"fieldType":"NORMAL","position":12},{"fieldType":"BONUS","position":13},{"fieldType":"NORMAL","position":14},{"fieldType":"TRAP","position":15},{"fieldType":"NORMAL","position":16},{"fieldType":"NORMAL","position":17},{"fieldType":"BONUS","position":18},{"fieldType":"BONUS","position":19},{"fieldType":"NORMAL","position":20},{"fieldType":"NORMAL","position":21},{"fieldType":"TRAP","position":22},{"fieldType":"BONUS","position":23},{"fieldType":"NORMAL","position":24},{"fieldType":"NORMAL","position":25},{"fieldType":"NORMAL","position":26},{"fieldType":"NORMAL","position":27},{"fieldType":"NORMAL","position":28},{"fieldType":"NORMAL","position":29},{"fieldType":"NORMAL","position":30}],"players":[{"name":"Player 3","field":9,"previousField":8,"joker":false,"skipNextRound":false,"lastGamingSituation":"Player 3 has hit a bonus field of the type 'All opponents have to move two fields backwards'. The player 'Player 3' moved from field number 8 to field number 9."},{"name":"Player 1","field":8,"previousField":10,"joker":false,"skipNextRound":false,"lastGamingSituation":"Player 1 was moved backwards automatically. The player 'Player 1' moved from field number 10 to field number 8."},{"name":"Player 2","field":9,"previousField":11,"joker":false,"skipNextRound":false,"lastGamingSituation":"Player 2 was moved backwards automatically. The player 'Player 2' moved from field number 11 to field number 9."}],"nextPlayer":{"name":"Player 1","field":8,"previousField":10,"joker":false,"skipNextRound":false,"lastGamingSituation":"Player 1 was moved backwards automatically. The player 'Player 1' moved from field number 10 to field number 8."},"winner":null,"id":"feb5d853-f51b-4744-a685-adb3d58f1449"},
  {"fields":[{"fieldType":"NORMAL","position":1},{"fieldType":"NORMAL","position":2},{"fieldType":"NORMAL","position":3},{"fieldType":"NORMAL","position":4},{"fieldType":"TRAP","position":5},{"fieldType":"NORMAL","position":6},{"fieldType":"TRAP","position":7},{"fieldType":"NORMAL","position":8},{"fieldType":"BONUS","position":9},{"fieldType":"NORMAL","position":10},{"fieldType":"TRAP","position":11},{"fieldType":"NORMAL","position":12},{"fieldType":"BONUS","position":13},{"fieldType":"NORMAL","position":14},{"fieldType":"TRAP","position":15},{"fieldType":"NORMAL","position":16},{"fieldType":"NORMAL","position":17},{"fieldType":"BONUS","position":18},{"fieldType":"BONUS","position":19},{"fieldType":"NORMAL","position":20},{"fieldType":"NORMAL","position":21},{"fieldType":"TRAP","position":22},{"fieldType":"BONUS","position":23},{"fieldType":"NORMAL","position":24},{"fieldType":"NORMAL","position":25},{"fieldType":"NORMAL","position":26},{"fieldType":"NORMAL","position":27},{"fieldType":"NORMAL","position":28},{"fieldType":"NORMAL","position":29},{"fieldType":"NORMAL","position":30}],"players":[{"name":"Player 3","field":9,"previousField":8,"joker":false,"skipNextRound":false,"lastGamingSituation":"Player 3 has hit a bonus field of the type 'All opponents have to move two fields backwards'. The player 'Player 3' moved from field number 8 to field number 9."},{"name":"Player 1","field":13,"previousField":8,"joker":true,"skipNextRound":false,"lastGamingSituation":"Player 1 has hit a bonus field of the type 'Joker'. The player 'Player 1' moved from field number 8 to field number 13."},{"name":"Player 2","field":9,"previousField":11,"joker":false,"skipNextRound":false,"lastGamingSituation":"Player 2 was moved backwards automatically. The player 'Player 2' moved from field number 11 to field number 9."}],"nextPlayer":{"name":"Player 2","field":9,"previousField":11,"joker":false,"skipNextRound":false,"lastGamingSituation":"Player 2 was moved backwards automatically. The player 'Player 2' moved from field number 11 to field number 9."},"winner":null,"id":"feb5d853-f51b-4744-a685-adb3d58f1449"},
  {"fields":[{"fieldType":"NORMAL","position":1},{"fieldType":"NORMAL","position":2},{"fieldType":"NORMAL","position":3},{"fieldType":"NORMAL","position":4},{"fieldType":"TRAP","position":5},{"fieldType":"NORMAL","position":6},{"fieldType":"TRAP","position":7},{"fieldType":"NORMAL","position":8},{"fieldType":"BONUS","position":9},{"fieldType":"NORMAL","position":10},{"fieldType":"TRAP","position":11},{"fieldType":"NORMAL","position":12},{"fieldType":"BONUS","position":13},{"fieldType":"NORMAL","position":14},{"fieldType":"TRAP","position":15},{"fieldType":"NORMAL","position":16},{"fieldType":"NORMAL","position":17},{"fieldType":"BONUS","position":18},{"fieldType":"BONUS","position":19},{"fieldType":"NORMAL","position":20},{"fieldType":"NORMAL","position":21},{"fieldType":"TRAP","position":22},{"fieldType":"BONUS","position":23},{"fieldType":"NORMAL","position":24},{"fieldType":"NORMAL","position":25},{"fieldType":"NORMAL","position":26},{"fieldType":"NORMAL","position":27},{"fieldType":"NORMAL","position":28},{"fieldType":"NORMAL","position":29},{"fieldType":"NORMAL","position":30}],"players":[{"name":"Player 3","field":11,"previousField":9,"joker":false,"skipNextRound":false,"lastGamingSituation":"Player 3 was moved forward automatically. The player 'Player 3' moved from field number 9 to field number 11."},{"name":"Player 1","field":15,"previousField":13,"joker":true,"skipNextRound":false,"lastGamingSituation":"Player 1 was moved forward automatically. The player 'Player 1' moved from field number 13 to field number 15."},{"name":"Player 2","field":15,"previousField":9,"joker":false,"skipNextRound":false,"lastGamingSituation":"Player 2 has hit a trap field of the type 'All opponents move two fields forward'. The player 'Player 2' moved from field number 9 to field number 15."}],"nextPlayer":{"name":"Player 3","field":11,"previousField":9,"joker":false,"skipNextRound":false,"lastGamingSituation":"Player 3 was moved forward automatically. The player 'Player 3' moved from field number 9 to field number 11."},"winner":null,"id":"feb5d853-f51b-4744-a685-adb3d58f1449"},
  {"fields":[{"fieldType":"NORMAL","position":1},{"fieldType":"NORMAL","position":2},{"fieldType":"NORMAL","position":3},{"fieldType":"NORMAL","position":4},{"fieldType":"TRAP","position":5},{"fieldType":"NORMAL","position":6},{"fieldType":"TRAP","position":7},{"fieldType":"NORMAL","position":8},{"fieldType":"BONUS","position":9},{"fieldType":"NORMAL","position":10},{"fieldType":"TRAP","position":11},{"fieldType":"NORMAL","position":12},{"fieldType":"BONUS","position":13},{"fieldType":"NORMAL","position":14},{"fieldType":"TRAP","position":15},{"fieldType":"NORMAL","position":16},{"fieldType":"NORMAL","position":17},{"fieldType":"BONUS","position":18},{"fieldType":"BONUS","position":19},{"fieldType":"NORMAL","position":20},{"fieldType":"NORMAL","position":21},{"fieldType":"TRAP","position":22},{"fieldType":"BONUS","position":23},{"fieldType":"NORMAL","position":24},{"fieldType":"NORMAL","position":25},{"fieldType":"NORMAL","position":26},{"fieldType":"NORMAL","position":27},{"fieldType":"NORMAL","position":28},{"fieldType":"NORMAL","position":29},{"fieldType":"NORMAL","position":30}],"players":[{"name":"Player 3","field":17,"previousField":11,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 3' moved from field number 11 to field number 17."},{"name":"Player 1","field":15,"previousField":13,"joker":true,"skipNextRound":false,"lastGamingSituation":"Player 1 was moved forward automatically. The player 'Player 1' moved from field number 13 to field number 15."},{"name":"Player 2","field":15,"previousField":9,"joker":false,"skipNextRound":false,"lastGamingSituation":"Player 2 has hit a trap field of the type 'All opponents move two fields forward'. The player 'Player 2' moved from field number 9 to field number 15."}],"nextPlayer":{"name":"Player 1","field":15,"previousField":13,"joker":true,"skipNextRound":false,"lastGamingSituation":"Player 1 was moved forward automatically. The player 'Player 1' moved from field number 13 to field number 15."},"winner":null,"id":"feb5d853-f51b-4744-a685-adb3d58f1449"},
  {"fields":[{"fieldType":"NORMAL","position":1},{"fieldType":"NORMAL","position":2},{"fieldType":"NORMAL","position":3},{"fieldType":"NORMAL","position":4},{"fieldType":"TRAP","position":5},{"fieldType":"NORMAL","position":6},{"fieldType":"TRAP","position":7},{"fieldType":"NORMAL","position":8},{"fieldType":"BONUS","position":9},{"fieldType":"NORMAL","position":10},{"fieldType":"TRAP","position":11},{"fieldType":"NORMAL","position":12},{"fieldType":"BONUS","position":13},{"fieldType":"NORMAL","position":14},{"fieldType":"TRAP","position":15},{"fieldType":"NORMAL","position":16},{"fieldType":"NORMAL","position":17},{"fieldType":"BONUS","position":18},{"fieldType":"BONUS","position":19},{"fieldType":"NORMAL","position":20},{"fieldType":"NORMAL","position":21},{"fieldType":"TRAP","position":22},{"fieldType":"BONUS","position":23},{"fieldType":"NORMAL","position":24},{"fieldType":"NORMAL","position":25},{"fieldType":"NORMAL","position":26},{"fieldType":"NORMAL","position":27},{"fieldType":"NORMAL","position":28},{"fieldType":"NORMAL","position":29},{"fieldType":"NORMAL","position":30}],"players":[{"name":"Player 3","field":17,"previousField":11,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 3' moved from field number 11 to field number 17."},{"name":"Player 1","field":20,"previousField":15,"joker":true,"skipNextRound":false,"lastGamingSituation":"The player 'Player 1' moved from field number 15 to field number 20."},{"name":"Player 2","field":15,"previousField":9,"joker":false,"skipNextRound":false,"lastGamingSituation":"Player 2 has hit a trap field of the type 'All opponents move two fields forward'. The player 'Player 2' moved from field number 9 to field number 15."}],"nextPlayer":{"name":"Player 2","field":15,"previousField":9,"joker":false,"skipNextRound":false,"lastGamingSituation":"Player 2 has hit a trap field of the type 'All opponents move two fields forward'. The player 'Player 2' moved from field number 9 to field number 15."},"winner":null,"id":"feb5d853-f51b-4744-a685-adb3d58f1449"},
  {"fields":[{"fieldType":"NORMAL","position":1},{"fieldType":"NORMAL","position":2},{"fieldType":"NORMAL","position":3},{"fieldType":"NORMAL","position":4},{"fieldType":"TRAP","position":5},{"fieldType":"NORMAL","position":6},{"fieldType":"TRAP","position":7},{"fieldType":"NORMAL","position":8},{"fieldType":"BONUS","position":9},{"fieldType":"NORMAL","position":10},{"fieldType":"TRAP","position":11},{"fieldType":"NORMAL","position":12},{"fieldType":"BONUS","position":13},{"fieldType":"NORMAL","position":14},{"fieldType":"TRAP","position":15},{"fieldType":"NORMAL","position":16},{"fieldType":"NORMAL","position":17},{"fieldType":"BONUS","position":18},{"fieldType":"BONUS","position":19},{"fieldType":"NORMAL","position":20},{"fieldType":"NORMAL","position":21},{"fieldType":"TRAP","position":22},{"fieldType":"BONUS","position":23},{"fieldType":"NORMAL","position":24},{"fieldType":"NORMAL","position":25},{"fieldType":"NORMAL","position":26},{"fieldType":"NORMAL","position":27},{"fieldType":"NORMAL","position":28},{"fieldType":"NORMAL","position":29},{"fieldType":"NORMAL","position":30}],"players":[{"name":"Player 3","field":17,"previousField":11,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 3' moved from field number 11 to field number 17."},{"name":"Player 1","field":20,"previousField":15,"joker":true,"skipNextRound":false,"lastGamingSituation":"The player 'Player 1' moved from field number 15 to field number 20."},{"name":"Player 2","field":21,"previousField":15,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 2' moved from field number 15 to field number 21."}],"nextPlayer":{"name":"Player 3","field":17,"previousField":11,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 3' moved from field number 11 to field number 17."},"winner":null,"id":"feb5d853-f51b-4744-a685-adb3d58f1449"},
  {"fields":[{"fieldType":"NORMAL","position":1},{"fieldType":"NORMAL","position":2},{"fieldType":"NORMAL","position":3},{"fieldType":"NORMAL","position":4},{"fieldType":"TRAP","position":5},{"fieldType":"NORMAL","position":6},{"fieldType":"TRAP","position":7},{"fieldType":"NORMAL","position":8},{"fieldType":"BONUS","position":9},{"fieldType":"NORMAL","position":10},{"fieldType":"TRAP","position":11},{"fieldType":"NORMAL","position":12},{"fieldType":"BONUS","position":13},{"fieldType":"NORMAL","position":14},{"fieldType":"TRAP","position":15},{"fieldType":"NORMAL","position":16},{"fieldType":"NORMAL","position":17},{"fieldType":"BONUS","position":18},{"fieldType":"BONUS","position":19},{"fieldType":"NORMAL","position":20},{"fieldType":"NORMAL","position":21},{"fieldType":"TRAP","position":22},{"fieldType":"BONUS","position":23},{"fieldType":"NORMAL","position":24},{"fieldType":"NORMAL","position":25},{"fieldType":"NORMAL","position":26},{"fieldType":"NORMAL","position":27},{"fieldType":"NORMAL","position":28},{"fieldType":"NORMAL","position":29},{"fieldType":"NORMAL","position":30}],"players":[{"name":"Player 3","field":21,"previousField":17,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 3' moved from field number 17 to field number 21."},{"name":"Player 1","field":20,"previousField":15,"joker":true,"skipNextRound":false,"lastGamingSituation":"The player 'Player 1' moved from field number 15 to field number 20."},{"name":"Player 2","field":21,"previousField":15,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 2' moved from field number 15 to field number 21."}],"nextPlayer":{"name":"Player 1","field":20,"previousField":15,"joker":true,"skipNextRound":false,"lastGamingSituation":"The player 'Player 1' moved from field number 15 to field number 20."},"winner":null,"id":"feb5d853-f51b-4744-a685-adb3d58f1449"},
  {"fields":[{"fieldType":"NORMAL","position":1},{"fieldType":"NORMAL","position":2},{"fieldType":"NORMAL","position":3},{"fieldType":"NORMAL","position":4},{"fieldType":"TRAP","position":5},{"fieldType":"NORMAL","position":6},{"fieldType":"TRAP","position":7},{"fieldType":"NORMAL","position":8},{"fieldType":"BONUS","position":9},{"fieldType":"NORMAL","position":10},{"fieldType":"TRAP","position":11},{"fieldType":"NORMAL","position":12},{"fieldType":"BONUS","position":13},{"fieldType":"NORMAL","position":14},{"fieldType":"TRAP","position":15},{"fieldType":"NORMAL","position":16},{"fieldType":"NORMAL","position":17},{"fieldType":"BONUS","position":18},{"fieldType":"BONUS","position":19},{"fieldType":"NORMAL","position":20},{"fieldType":"NORMAL","position":21},{"fieldType":"TRAP","position":22},{"fieldType":"BONUS","position":23},{"fieldType":"NORMAL","position":24},{"fieldType":"NORMAL","position":25},{"fieldType":"NORMAL","position":26},{"fieldType":"NORMAL","position":27},{"fieldType":"NORMAL","position":28},{"fieldType":"NORMAL","position":29},{"fieldType":"NORMAL","position":30}],"players":[{"name":"Player 3","field":21,"previousField":17,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 3' moved from field number 17 to field number 21."},{"name":"Player 1","field":22,"previousField":20,"joker":false,"skipNextRound":false,"lastGamingSituation":"Player 1 has hit a trap field of the type 'Move two fields backwards'. The player used its joker and stays put."},{"name":"Player 2","field":21,"previousField":15,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 2' moved from field number 15 to field number 21."}],"nextPlayer":{"name":"Player 2","field":21,"previousField":15,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 2' moved from field number 15 to field number 21."},"winner":null,"id":"feb5d853-f51b-4744-a685-adb3d58f1449"},
  {"fields":[{"fieldType":"NORMAL","position":1},{"fieldType":"NORMAL","position":2},{"fieldType":"NORMAL","position":3},{"fieldType":"NORMAL","position":4},{"fieldType":"TRAP","position":5},{"fieldType":"NORMAL","position":6},{"fieldType":"TRAP","position":7},{"fieldType":"NORMAL","position":8},{"fieldType":"BONUS","position":9},{"fieldType":"NORMAL","position":10},{"fieldType":"TRAP","position":11},{"fieldType":"NORMAL","position":12},{"fieldType":"BONUS","position":13},{"fieldType":"NORMAL","position":14},{"fieldType":"TRAP","position":15},{"fieldType":"NORMAL","position":16},{"fieldType":"NORMAL","position":17},{"fieldType":"BONUS","position":18},{"fieldType":"BONUS","position":19},{"fieldType":"NORMAL","position":20},{"fieldType":"NORMAL","position":21},{"fieldType":"TRAP","position":22},{"fieldType":"BONUS","position":23},{"fieldType":"NORMAL","position":24},{"fieldType":"NORMAL","position":25},{"fieldType":"NORMAL","position":26},{"fieldType":"NORMAL","position":27},{"fieldType":"NORMAL","position":28},{"fieldType":"NORMAL","position":29},{"fieldType":"NORMAL","position":30}],"players":[{"name":"Player 3","field":21,"previousField":17,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 3' moved from field number 17 to field number 21."},{"name":"Player 1","field":22,"previousField":20,"joker":false,"skipNextRound":false,"lastGamingSituation":"Player 1 has hit a trap field of the type 'Move two fields backwards'. The player used its joker and stays put."},{"name":"Player 2","field":26,"previousField":21,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 2' moved from field number 21 to field number 26."}],"nextPlayer":{"name":"Player 3","field":21,"previousField":17,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 3' moved from field number 17 to field number 21."},"winner":null,"id":"feb5d853-f51b-4744-a685-adb3d58f1449"},
  {"fields":[{"fieldType":"NORMAL","position":1},{"fieldType":"NORMAL","position":2},{"fieldType":"NORMAL","position":3},{"fieldType":"NORMAL","position":4},{"fieldType":"TRAP","position":5},{"fieldType":"NORMAL","position":6},{"fieldType":"TRAP","position":7},{"fieldType":"NORMAL","position":8},{"fieldType":"BONUS","position":9},{"fieldType":"NORMAL","position":10},{"fieldType":"TRAP","position":11},{"fieldType":"NORMAL","position":12},{"fieldType":"BONUS","position":13},{"fieldType":"NORMAL","position":14},{"fieldType":"TRAP","position":15},{"fieldType":"NORMAL","position":16},{"fieldType":"NORMAL","position":17},{"fieldType":"BONUS","position":18},{"fieldType":"BONUS","position":19},{"fieldType":"NORMAL","position":20},{"fieldType":"NORMAL","position":21},{"fieldType":"TRAP","position":22},{"fieldType":"BONUS","position":23},{"fieldType":"NORMAL","position":24},{"fieldType":"NORMAL","position":25},{"fieldType":"NORMAL","position":26},{"fieldType":"NORMAL","position":27},{"fieldType":"NORMAL","position":28},{"fieldType":"NORMAL","position":29},{"fieldType":"NORMAL","position":30}],"players":[{"name":"Player 3","field":22,"previousField":21,"joker":false,"skipNextRound":true,"lastGamingSituation":"Player 3 has hit a trap field of the type 'Skip next turn'. The player 'Player 3' moved from field number 21 to field number 22."},{"name":"Player 1","field":22,"previousField":20,"joker":false,"skipNextRound":false,"lastGamingSituation":"Player 1 has hit a trap field of the type 'Move two fields backwards'. The player used its joker and stays put."},{"name":"Player 2","field":26,"previousField":21,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 2' moved from field number 21 to field number 26."}],"nextPlayer":{"name":"Player 1","field":22,"previousField":20,"joker":false,"skipNextRound":false,"lastGamingSituation":"Player 1 has hit a trap field of the type 'Move two fields backwards'. The player used its joker and stays put."},"winner":null,"id":"feb5d853-f51b-4744-a685-adb3d58f1449"},
  {"fields":[{"fieldType":"NORMAL","position":1},{"fieldType":"NORMAL","position":2},{"fieldType":"NORMAL","position":3},{"fieldType":"NORMAL","position":4},{"fieldType":"TRAP","position":5},{"fieldType":"NORMAL","position":6},{"fieldType":"TRAP","position":7},{"fieldType":"NORMAL","position":8},{"fieldType":"BONUS","position":9},{"fieldType":"NORMAL","position":10},{"fieldType":"TRAP","position":11},{"fieldType":"NORMAL","position":12},{"fieldType":"BONUS","position":13},{"fieldType":"NORMAL","position":14},{"fieldType":"TRAP","position":15},{"fieldType":"NORMAL","position":16},{"fieldType":"NORMAL","position":17},{"fieldType":"BONUS","position":18},{"fieldType":"BONUS","position":19},{"fieldType":"NORMAL","position":20},{"fieldType":"NORMAL","position":21},{"fieldType":"TRAP","position":22},{"fieldType":"BONUS","position":23},{"fieldType":"NORMAL","position":24},{"fieldType":"NORMAL","position":25},{"fieldType":"NORMAL","position":26},{"fieldType":"NORMAL","position":27},{"fieldType":"NORMAL","position":28},{"fieldType":"NORMAL","position":29},{"fieldType":"NORMAL","position":30}],"players":[{"name":"Player 3","field":22,"previousField":21,"joker":false,"skipNextRound":true,"lastGamingSituation":"Player 3 has hit a trap field of the type 'Skip next turn'. The player 'Player 3' moved from field number 21 to field number 22."},{"name":"Player 1","field":24,"previousField":22,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 1' moved from field number 22 to field number 24."},{"name":"Player 2","field":26,"previousField":21,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 2' moved from field number 21 to field number 26."}],"nextPlayer":{"name":"Player 2","field":26,"previousField":21,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 2' moved from field number 21 to field number 26."},"winner":null,"id":"feb5d853-f51b-4744-a685-adb3d58f1449"},
  {"fields":[{"fieldType":"NORMAL","position":1},{"fieldType":"NORMAL","position":2},{"fieldType":"NORMAL","position":3},{"fieldType":"NORMAL","position":4},{"fieldType":"TRAP","position":5},{"fieldType":"NORMAL","position":6},{"fieldType":"TRAP","position":7},{"fieldType":"NORMAL","position":8},{"fieldType":"BONUS","position":9},{"fieldType":"NORMAL","position":10},{"fieldType":"TRAP","position":11},{"fieldType":"NORMAL","position":12},{"fieldType":"BONUS","position":13},{"fieldType":"NORMAL","position":14},{"fieldType":"TRAP","position":15},{"fieldType":"NORMAL","position":16},{"fieldType":"NORMAL","position":17},{"fieldType":"BONUS","position":18},{"fieldType":"BONUS","position":19},{"fieldType":"NORMAL","position":20},{"fieldType":"NORMAL","position":21},{"fieldType":"TRAP","position":22},{"fieldType":"BONUS","position":23},{"fieldType":"NORMAL","position":24},{"fieldType":"NORMAL","position":25},{"fieldType":"NORMAL","position":26},{"fieldType":"NORMAL","position":27},{"fieldType":"NORMAL","position":28},{"fieldType":"NORMAL","position":29},{"fieldType":"NORMAL","position":30}],"players":[{"name":"Player 3","field":22,"previousField":21,"joker":false,"skipNextRound":false,"lastGamingSituation":"Player 3 has skipped its turn and stays on field number 22."},{"name":"Player 1","field":24,"previousField":22,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 1' moved from field number 22 to field number 24."},{"name":"Player 2","field":28,"previousField":26,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 2' moved from field number 26 to field number 28."}],"nextPlayer":{"name":"Player 1","field":24,"previousField":22,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 1' moved from field number 22 to field number 24."},"winner":null,"id":"feb5d853-f51b-4744-a685-adb3d58f1449"},
  {"fields":[{"fieldType":"NORMAL","position":1},{"fieldType":"NORMAL","position":2},{"fieldType":"NORMAL","position":3},{"fieldType":"NORMAL","position":4},{"fieldType":"TRAP","position":5},{"fieldType":"NORMAL","position":6},{"fieldType":"TRAP","position":7},{"fieldType":"NORMAL","position":8},{"fieldType":"BONUS","position":9},{"fieldType":"NORMAL","position":10},{"fieldType":"TRAP","position":11},{"fieldType":"NORMAL","position":12},{"fieldType":"BONUS","position":13},{"fieldType":"NORMAL","position":14},{"fieldType":"TRAP","position":15},{"fieldType":"NORMAL","position":16},{"fieldType":"NORMAL","position":17},{"fieldType":"BONUS","position":18},{"fieldType":"BONUS","position":19},{"fieldType":"NORMAL","position":20},{"fieldType":"NORMAL","position":21},{"fieldType":"TRAP","position":22},{"fieldType":"BONUS","position":23},{"fieldType":"NORMAL","position":24},{"fieldType":"NORMAL","position":25},{"fieldType":"NORMAL","position":26},{"fieldType":"NORMAL","position":27},{"fieldType":"NORMAL","position":28},{"fieldType":"NORMAL","position":29},{"fieldType":"NORMAL","position":30}],"players":[{"name":"Player 3","field":22,"previousField":21,"joker":false,"skipNextRound":false,"lastGamingSituation":"Player 3 has skipped its turn and stays on field number 22."},{"name":"Player 1","field":28,"previousField":24,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 1' moved from field number 24 to field number 28."},{"name":"Player 2","field":28,"previousField":26,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 2' moved from field number 26 to field number 28."}],"nextPlayer":{"name":"Player 2","field":28,"previousField":26,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 2' moved from field number 26 to field number 28."},"winner":null,"id":"feb5d853-f51b-4744-a685-adb3d58f1449"},
  {"fields":[{"fieldType":"NORMAL","position":1},{"fieldType":"NORMAL","position":2},{"fieldType":"NORMAL","position":3},{"fieldType":"NORMAL","position":4},{"fieldType":"TRAP","position":5},{"fieldType":"NORMAL","position":6},{"fieldType":"TRAP","position":7},{"fieldType":"NORMAL","position":8},{"fieldType":"BONUS","position":9},{"fieldType":"NORMAL","position":10},{"fieldType":"TRAP","position":11},{"fieldType":"NORMAL","position":12},{"fieldType":"BONUS","position":13},{"fieldType":"NORMAL","position":14},{"fieldType":"TRAP","position":15},{"fieldType":"NORMAL","position":16},{"fieldType":"NORMAL","position":17},{"fieldType":"BONUS","position":18},{"fieldType":"BONUS","position":19},{"fieldType":"NORMAL","position":20},{"fieldType":"NORMAL","position":21},{"fieldType":"TRAP","position":22},{"fieldType":"BONUS","position":23},{"fieldType":"NORMAL","position":24},{"fieldType":"NORMAL","position":25},{"fieldType":"NORMAL","position":26},{"fieldType":"NORMAL","position":27},{"fieldType":"NORMAL","position":28},{"fieldType":"NORMAL","position":29},{"fieldType":"NORMAL","position":30}],"players":[{"name":"Player 3","field":22,"previousField":21,"joker":false,"skipNextRound":false,"lastGamingSituation":"Player 3 has skipped its turn and stays on field number 22."},{"name":"Player 1","field":28,"previousField":24,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 1' moved from field number 24 to field number 28."},{"name":"Player 2","field":33,"previousField":28,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 2' moved from field number 26 to field number 28."}],"nextPlayer":null,"winner":{"name":"Player 2","field":33,"previousField":28,"joker":false,"skipNextRound":false,"lastGamingSituation":"The player 'Player 2' moved from field number 26 to field number 28."},"id":"feb5d853-f51b-4744-a685-adb3d58f1449"}
];

const makeRangeIterator = (start = 0, end = Infinity, step = 1) => {
  let nextIndex = start;

  const rangeIterator = {
    next() {
      let result;
      if (nextIndex < end) {
        result = { value: NEXT[nextIndex], done: false };
        nextIndex += step;
        return result;
      }
      return { value: 'bad request', done: true };
    }
  };
  return rangeIterator;
};

let it, result = undefined;

export const getStart = async () => {
  it = makeRangeIterator(0, NEXT.length);
  result = {done: false};
  const response = await Promise.resolve({text: () => Promise.resolve(START)});
  return response.text();
};

export const createPlayers = async (id, numberOfPlayers) => {
  const response = await Promise.resolve({json: () => Promise.resolve(CREATE_PLAYERS)});
  return response.json();
};

export const nextRound = async (id, player, numberOfDice) => {
  if (!result.done) {
    result = it.next();
    const response = await Promise.resolve({json: () => Promise.resolve(result.value)});
    return response.json();
  }
  return result.value;
};
